### ISSUE TITLE
Add KNN to the library

### ISSUE THREAD

**Issue by popigg** [ml-uem/data-sci-lab#33]
It would be great if the library could have KNN algorithm too. 
[https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm](Here) is the reference where algorithm and error rates are explained.

**Comment by JuanLuisTrejo** [comment]
I have worked the KNN algorithm this week. Already checked with a local dataset find below the code:

`#KNN neighbor Algorithm

import numpy as np
import pandas as pd
#Euclidea Distance
def DistEuclidea (dato,dato1):
    x=0
    for i in range(len(dato1.columns)-1):
        x += (((dato.iloc[0,i] - dato1.iloc[:,i])**2))
    return np.sqrt(x)

print (DistEuclidea (dato,Data2))

#Clasify. Get the nearest  k neighbors. Predict the value considering neighbors
def Neighbors (k):
    y = (DistEuclidea (dato , Data2))
    #Classify 
    while len(y)>k:
        z = y.idxmax()
        y.pop(z)
    #Predict
    return y.mean()
print (Neighbors(3))# Predict value

 `

**Comment by lumartin** [comment]
Great job! This weekend we will be able to refactor the code and add it to the library. Thanks!

**Comment by popigg** [comment]
🚀 🚀 🚀 go go go @JuanLuisTrejo

**Comment by JuanLuisTrejo** [comment]
`#KNN neighbor Algorithm

import numpy as np
import pandas as pd
#Euclidea Distance
def DistEuclidea (dato,dato1):
x=0
for i in range(len(dato1.columns)-1):
x += (((dato.iloc[0,i] - dato1.iloc[:,i])**2))
return np.sqrt(x)

print (DistEuclidea (dato,Data2))

#Clasify. Get the nearest k neighbors. Predict the value considering neighbors
def Neighbors (k):
y = (DistEuclidea (dato , Data2))
#Classify
while len(y)>k:
z = y.idxmax()
y.pop(z)
#Predict
return (y.mean(),y)
print (Neighbors(3))# Predict value

**Comment by JuanLuisTrejo** [comment]
Returning along with the Prediction the Classification (K Nearest Neighbors). 3 in the example

**Comment by popigg** [comment]
It looks like we can close the issue
